version: '3.5'

services:
#  nodejs:
#    container_name: nodejs
#    build:
#      context: .
#    env_file:
#      - .env
#    volumes:
#      - .:/app
#      - node_modules:/app/node_modules
#    ports:
#      - "5000:5000"
#    depends_on:
#      - postgres
#    restart: always

  postgres:
    container_name: postgres
    image: postgres:14.3-alpine3.16
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $DATABASE_NAME
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
#  node_modules: